### ISSUE TITLE
`<windows.h>` should not be exposed to users

### ISSUE THREAD

**Issue by milleniumbug** [eidheim/tiny-process-library#12]
`<windows.h>` is included on Windows in the header file. This is problematic for users, as `<windows.h>` has a bad reputation - for example, your calls to `std::min()` [will stop working if it's included](https://stackoverflow.com/questions/11544073/how-do-i-deal-with-the-max-macro-in-windows-h-colliding-with-max-in-std). The specific problem of non-working `std::min` be fixed by defining `NOMINMAX`, but there are many more `#define`s in there. The general problem can be fixed by using PIMPL idiom and moving away the `#include <windows.h>` to the implementation file.

**Comment by eidheim** [comment]
The best solution here is to deftype id_type, fd_type and string_type manually for Windows in process.hpp maybe?

**Comment by eidheim** [comment]
Something like this:
```c++
  typedef unsigned long id_type
  typedef void* fd_type
#ifdef UNICODE
  typedef std::wstring string_type
#else
  typedef std::string string_type
#ifdef
```
?

**Comment by milleniumbug** [comment]
That will do. I assume Microsoft won't ever change what `HANDLE` is typedef'd to, but you can protect yourself even from that scenario: In the implementation file have `static_assert(std::is_same<fd_type, HANDLE>::value, "change your fd_type");`, so if the type is ever different, you can get clear compile time message.

**Comment by nabijaczleweli** [comment]
```cpp
namespace windooze {
    #include <windows.h>
}
```

**Comment by eidheim** [comment]
@nabijaczleweli good suggestion, but I'm not 100% sure this works with the clang compiler.

**Comment by milleniumbug** [comment]
@nabijaczleweli No, that's a terrible suggestion. How does that protect your codebase from shitty macros? Also it doesn't really work for functions with `extern "C"` linkage, which is most of the `<windows.h>`.

**Comment by nabijaczleweli** [comment]
`#undef min`, `#undef max`

**Comment by milleniumbug** [comment]
Now, generalize that for all non-hygienic macros (that means, using at least one lowercase letter) defined there, and we can start considering this as a viable solution. I actually have an project idea of a header `<unwindows.h>` which undefines all of them, but it's unfinished (inspired by POCO's Unwindows.h, but it undefines only a selected subset of it which they use)

It's simpler to just compile-firewall it.

**Comment by eidheim** [comment]
We could move `fd_type` out of the `process.hpp` header completely (having `std::unique_ptr<fd_type> stdout_fd, stderr_fd, stdin_fd;` in each implementation, though `id_type` is still needed. Does including `IntSafe.h` have the same problems (https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx, search for `DWORD`)?

**Comment by eidheim** [comment]
I decided to go with my first suggestion, hoping Windows goes POSIX before changing the HANDLE typedef!

**Comment by nabijaczleweli** [comment]
The API will be stable for at least the next 20 years, so no problems there
