### ISSUE TITLE
how can i set enviroment var for process?

### ISSUE THREAD

**Issue by sixleaves** [eidheim/tiny-process-library#19]
how can i set enviroment var for process?how can i set enviroment var for process?

**Comment by eidheim** [comment]
Typically one would write something like `Process process("TEST=1 env", ...)`. You can replace `env` with your program. The child process also gets the enviroment of the parent process, so you can use [setenv](http://pubs.opengroup.org/onlinepubs/009695399/functions/setenv.html) as well before starting the child process.
