### ISSUE TITLE
C++ namespace?

### ISSUE THREAD

**Issue by kainjow** [eidheim/tiny-process-library#20]
I just realized the Process class is in the global namespace. Maybe one should be added, to limit scope, since "Process" is fairly generic.

**Comment by eidheim** [comment]
I decided to drop a namespace since this library only contains one class, but you are right, we should probably have a namespace. Now the main problem is what we should call this namespace.

**Comment by kainjow** [comment]
You could use your username.

**Comment by InusualZ** [comment]
`tp` as TinyProcess?

**Comment by grasmanek94** [comment]
`eidheim::tp::`

`tp` itself is too generic and I would appreciate if it were avoided (to avoid clashes if anyone decides to use `tp` anyway).

**Comment by eidheim** [comment]
Thank you for your suggestions, but how about `Tiny::`, `TinyProcess::` or `TinyProcessLibrary::`? I'm leaning towards `Tiny::` but this namespace is too generic as well, maybe my vote goes to `TinyProcess::`. Also, I'm used to CamelCase in class/class like names (like namespaces) and snake_case elsewhere, but not sure how common this is anymore.

**Comment by foonathan** [comment]
I'd say you go for a longer namespace name, users can alias it, if they want.

**Comment by grasmanek94** [comment]
Well my stance would be, if the namespace begins with something unique to each developer (e.g. boost uses `boost`, other developers use `username` or some `mainproject` namespace) then what comes after I totally don't mind. be it `tpl` or `Tiny` or `TinyProcess` or `TinyProcessLibrary` or `tp` or `tiny_process`.. :) `tp` could be a 'shot myself in the foot' choice in the future.. for example if you make a `ToiletPaper` library! (that could be `tp` or `tpl` too)

**Comment by foonathan** [comment]
Well, that's what I think, too: http://foonathan.net/blog/2016/01/26/namespace-alias.html ;)

**Comment by eidheim** [comment]
Alright, I think I have finally decided: TinyProcessLib

That is, I'm going with Gtkmm/Gdkmm/Glibmm's CamelCase for namespaces and classes, and snake_case elsewhere. TensorFlow for instance uses lowercase for namespace and Gtkmm/Gdkmm/Glibmm style elsewhere, which looks a bit weird, but then again LLVM uses the same style as TensorFlow. My argument is that namespace and class/stuct are somewhat related, but feel free to argue with me on this!

Now the next question is, since we now would kinda break backward compatibility, should we bump the version to v2.0.0, or is v1.1.0 enough in this case?

**Comment by eidheim** [comment]
And I forgot: thank you all for your valuable input!

**Comment by kainjow** [comment]
I say go 2.0 to keep semantic versioning.

**Comment by eidheim** [comment]
Would have to bump to 2.0 yes, and sorry for this taking so long. I'm currently considering if there are other backward compatibility breaking things I would like to do before a major version bump. And of course I'll do a minute version bump release before this happens.
