### ISSUE TITLE
CloseHandle called on invalid handles

### ISSUE THREAD

**Issue by 5cript** [eidheim/tiny-process-library#29]
https://github.com/eidheim/tiny-process-library/blob/a034812647a89e924c9114db9f2d4c89c70226d1/process_win.cpp#L110-L111

These handles are invalid here and should not be closed. This will overwrite "GetLastError" with 6 = "Invalid Handle", so reading the error value to see what went wrong becomes impossible.

**Comment by eidheim** [comment]
Thank you for reporting this. Fixed as you proposed in the above commit.
